name: Auto-label PRs from Cursor

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add automerge label for trusted PR authors
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request
            const author = pr.user.login
            const trustedAuthors = (process.env.TRUSTED_AUTO_LABEL_AUTHORS || '').split(',').map(s => s.trim()).filter(Boolean)
            if (trustedAuthors.includes(author)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['automerge']
              })
            }
        env:
          TRUSTED_AUTO_LABEL_AUTHORS: ${{ secrets.TRUSTED_AUTO_LABEL_AUTHORS }}

